// Plain table metadata used by the Prisma-backed Drizzle compatibility layer.

export const usersTable = {
  model: "user",
  table: "users",
  columns: {
    id: "id",
    name: "name",
    userId: "userId",
    role: "role",
    email: "email",
  },
  id: "id",
  name: "name",
  userId: "userId",
  role: "role",
  email: "email",
};

export const destinations = {
  model: "destination",
  table: "destinations",
  columns: {
    id: "id",
    name: "name",
    country: "country",
    city: "city",
    description: "description",
    highlights: "highlights",
    bestSeason: "bestSeason",
    activities: "activities",
    price: "price",
    duration: "duration",
    imageUrl: "imageUrl",
  },
  id: "id",
  name: "name",
  country: "country",
  city: "city",
  description: "description",
  highlights: "highlights",
  bestSeason: "bestSeason",
  activities: "activities",
  price: "price",
  duration: "duration",
  imageUrl: "imageUrl",
};

export const checkout = {
  model: "checkout",
  table: "checkout",
  columns: {
    id: "id",
    firstName: "firstName",
    lastName: "lastName",
    email: "email",
    phone: "phone",
    checkInDate: "checkInDate",
    checkOutDate: "checkOutDate",
    travelers: "travelers",
    price: "price",
  },
  id: "id",
  firstName: "firstName",
  lastName: "lastName",
  email: "email",
  phone: "phone",
  checkInDate: "checkInDate",
  checkOutDate: "checkOutDate",
  travelers: "travelers",
  price: "price",
};
